### ISSUE TITLE
Not working on fresh install of Win

### ISSUE THREAD

**Issue by oliverban** [Aeoll/FFmpegify#7]
Hey!

I've used it for a while, all working great. Had to do a fresh install of windows and now it ain't working no more.

Checklist:
- I have ffmpeg installed correctly with it in the path and CMD recognizes it and shows the version upon writing "ffmpeg -version"
- I have installed all requirements and they are met.
- I have configured the paths in the reg file upon merging the regfile.

I can see FFmpegify in the context menu, and I can open up the settings as well from that menu when not clicking any file. Just like usual.

But men trying to make an MP4 into an JPG sequence like I've done multiple times I get:

Traceback (most recent call last):
  File "C:\FFmpegify\ffmpegify.py", line 399, in <module>
    F.convert(sys.argv[1])
  File "C:\FFmpegify\ffmpegify.py", line 317, in convert
    self.get_metadata(infile)
  File "C:\FFmpegify\ffmpegify.py", line 56, in get_metadata
    ffprobeInfo = ffmpeg.probe(str(inputf), v = "quiet")
AttributeError: module 'ffmpeg' has no attribute 'probe'

It really sucks because this little gem is awesome! I really love it and it's a great time saver so ANY help would be appreciated!! <3 <3 <3

**Comment by m-dr** [comment]
Have you found a solution? Having the same issue.
